STOP REPLICA;

CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='mysql-master',
  SOURCE_USER='replica',
  SOURCE_PASSWORD='replica_pass',
  SOURCE_LOG_FILE='mysql-bin.000003',   
  SOURCE_LOG_POS=832;

START REPLICA;

SHOW REPLICA STATUS\G;
